language: java

notifications:
  email: false

jdk:
- oraclejdk10


after_success:
- bash <(curl -s https://scripts.scantist.com/ci-travis.sh)
#- bash <(curl -s https://scripts.scantist.com/staging/ci-travis-jar-k8s.sh)
